### ISSUE TITLE
np.float128 error in xrtGlow

### ISSUE THREAD

**Issue by allthedata** [kklmn/xrt#18]
I'm running Windows 10, Anaconda 5.1.0, and the xrt master from github. I installed pyopencl and pyopengl from Gohlke. When I run xrtQookStart, open the lens3.xml example, and start xrtGlow, I get the following error:

```python
Traceback (most recent call last):

  File "..\..\xrt\gui\xrtGlow\__init__.py", line 2191, in paintGL
    pModel = np.array(gl.glGetDoublev(gl.GL_MODELVIEW_MATRIX))[:-1, :-1]

  File "C:\Users\user\AppData\Local\Continuum\Anaconda3\envs\python2\lib\site-packages\OpenGL\latebind.py", line 45, in __call__
    return self._finalCall( *args, **named )

  File "C:\Users\user\AppData\Local\Continuum\Anaconda3\envs\python2\lib\site-packages\OpenGL\wrapper.py", line 664, in wrapperCall
    cArgs = tuple(calculate_cArgs( pyArgs ))

  File "C:\Users\user\AppData\Local\Continuum\Anaconda3\envs\python2\lib\site-packages\OpenGL\wrapper.py", line 467, in calculate_cArgs
    yield converter( pyArgs, index, self )

  File "C:\Users\user\AppData\Local\Continuum\Anaconda3\envs\python2\lib\site-packages\OpenGL\converters.py", line 251, in __call__
    return super( SizedOutputOrInput,self ).__call__( pyArgs, index, baseOperation )

  File "C:\Users\user\AppData\Local\Continuum\Anaconda3\envs\python2\lib\site-packages\OpenGL\converters.py", line 196, in __call__
    return self.arrayType.zeros( self.getSize(pyArgs) )

  File "C:\Users\user\AppData\Local\Continuum\Anaconda3\envs\python2\lib\site-packages\OpenGL\arrays\arraydatatype.py", line 177, in zeros
    return cls.returnHandler().zeros( dims, typeCode or cls.typeConstant )

  File "C:\Users\user\AppData\Local\Continuum\Anaconda3\envs\python2\lib\site-packages\OpenGL\arrays\arraydatatype.py", line 80, in get_output_handler
    self.output_handler = self.handler_by_plugin_name( preferred )

  File "C:\Users\user\AppData\Local\Continuum\Anaconda3\envs\python2\lib\site-packages\OpenGL\arrays\arraydatatype.py", line 67, in handler_by_plugin_name
    return plugin.load()

  File "C:\Users\user\AppData\Local\Continuum\Anaconda3\envs\python2\lib\site-packages\OpenGL\plugins.py", line 16, in load
    return importByName( self.import_path )

  File "C:\Users\user\AppData\Local\Continuum\Anaconda3\envs\python2\lib\site-packages\OpenGL\plugins.py", line 38, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)

  File "C:\Users\user\AppData\Local\Continuum\Anaconda3\envs\python2\lib\site-packages\OpenGL\arrays\numpymodule.py", line 68, in <module>
    class NumpyHandler( formathandler.FormatHandler ):

  File "C:\Users\user\AppData\Local\Continuum\Anaconda3\envs\python2\lib\site-packages\OpenGL\arrays\numpymodule.py", line 93, in NumpyHandler
    numpy.float128,

AttributeError: ("'module' object has no attribute 'float128'", 'Failure in cConverter <OpenGL.converters.SizedOutputOrInput object at 0x00000000118315C8>', (GL_MODELVIEW_MATRIX, <object object at 0x00000000116F2780>), 1, <OpenGL.platform.baseplatform.glGetDoublev object at 0x0000000011A0FE08>)
```

Then I only see a black screen in the xrtGlow window, and keep getting these float128 errors when I enable optical elements.

I tried Python 3.6 64-bit, Python 2.7 64-bit, and Python 2.7 32-bit versions of Anaconda with the most recent matching versions of pyopencl and pyopengl from Gohlke, and got the same error. Of course if I use the versions in conda-forge, I get a `NullFunctionError: Attempt to call an undefined function glutBitmapCharacter, check for bool(glutBitmapCharacter) before calling` error similar to what is mentioned in https://github.com/kklmn/xrt/issues/14.

**Comment by kklmn** [comment]
At the top of the Gohlke's page there are recommendations on MS VC++ versions. Check that you have the right one. If not, get it and try to reinstall PyOpenGL again. If doesn't help, remove it and try to install PyOpenGL from the source, i.e. without giving pip a whl file. Maybe then it will complain about something missing.

**Comment by allthedata** [comment]
Installing pyopengl from the source worked, thanks!
