### ISSUE TITLE
xrtGlow fails to load a new xml after working with a previous one

### ISSUE THREAD

**Issue by kklmn** [kklmn/xrt#20]
Load BioXAS_Main.xml, put the virtual screen, close xrtGlow, load another xml.

QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
Traceback (most recent call last):
  File "..\..\xrt\gui\xrtQook\__init_.py", line 3366, in blRunGlow
    self.blViewer.updateOEsList(self.rayPath)
  File "..\..\xrt\gui\xrtGlow\__init_.py", line 687, in updateOEsList
    self.changeColorAxis(None)
  File "..\..\xrt\gui\xrtGlow\__init_.py", line 983, in changeColorAxis
    self.customGlWidget.populateVerticesArray(self.segmentsModelRoot)
  File "..\..\xrt\gui\xrtGlow\__init_.py", line 2116, in populateVerticesArray
    self.populateVScreen()
  File "..\..\xrt\gui\xrtGlow\__init__.py", line 3655, in populateVScreen
    vColorArray <= self.selColorMax,
TypeError: '<=' not supported between instances of 'float' and 'NoneType'

**Comment by yxrmz** [comment]
It's because the virtual screen is still on, but the rest of the beamline doesn't exist. A temporary workaround would be to disable the virtual screen before loading the beamline XML.
