### ISSUE TITLE
The error of using the backend of shadow operate the data from the shadow 

### ISSUE THREAD

**Issue by Zeng24** [kklmn/xrt#47]
I am sorry to disturbe you. I am interested to using the xrt operate using the backend of shadow.The problem is when I operate the code (below the paragraph) in Python3.7 without opencl but opengl，there is a error I can't solve :
```
(py37) D:\shadow>python 00_simple.py
('not readable',) , ignored...
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\anaconda\envs\py37\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "D:\anaconda\envs\py37\lib\tkinter\__init__.py", line 746, in callit
    func(*args)
  File "D:\anaconda\envs\py37\lib\site-packages\matplotlib\backends\_backend_tk.py", line 118, in _on_timer
    TimerBase._on_timer(self)
  File "D:\anaconda\envs\py37\lib\site-packages\matplotlib\backend_bases.py", line 1194, in _on_timer
    ret = func(*args, **kwargs)
  File "D:\anaconda\envs\py37\lib\site-packages\xrt\plotter.py", line 1093, in timer_callback
    runner.dispatch_jobs()
  File "D:\anaconda\envs\py37\lib\site-packages\xrt\runner.py", line 188, in dispatch_jobs
    plot.plot_plots()
  File "D:\anaconda\envs\py37\lib\site-packages\xrt\plotter.py", line 1606, in plot_plots
    intensityStr = r'$I = $' + fluxFormatStr
UnboundLocalError: local variable 'fluxFormatStr' referenced before assignment
```

the running code is 

```
import xrt.runner as xrtr

import xrt.plotter as xrtp

plot1 = xrtp.XYCPlot('star.01')

xrtr.run_ray_tracing(plot1, repeats=40, updateEvery=2, backend='shadow')
```
the tmp0 at the same folder of the code

**Comment by kklmn** [comment]
Hi,
Thank you for reporting the error! And sorry for the bug, we don't use this backend and haven't tested it for a long time.
I've fixed the bug, please get the new version of plotter.py or of the whole xrt and give it a try.

**Comment by Zeng24** [comment]
I am sorry to disturbe you again about the problem in operating xrt with shadow. It is important to me.
When I operate the code in the Page https://xrt.readthedocs.io/shadow.html#scriptingshadow
```
import xrt.runner as xrtr
import xrt.plotter as xrtp
plot1 = xrtp.XYCPlot('star.01')
xrtr.run_ray_tracing(plot1, repeats=40, updateEvery=2, threads=1)
```
there will be something wrong
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\anaconda\envs\py37\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "D:\anaconda\envs\py37\lib\tkinter\__init__.py", line 746, in callit
    func(*args)
  File "D:\anaconda\envs\py37\lib\site-packages\matplotlib\backends\_backend_tk.py", line 118, in _on_timer
    TimerBase._on_timer(self)
  File "D:\anaconda\envs\py37\lib\site-packages\matplotlib\backend_bases.py", line 1194, in _on_timer
    ret = func(*args, **kwargs)
  File "D:\anaconda\envs\py37\lib\site-packages\xrt\plotter.py", line 1097, in timer_callback
    runner.dispatch_jobs()
  File "D:\anaconda\envs\py37\lib\site-packages\xrt\runner.py", line 181, in dispatch_jobs
    one_iteration()
  File "D:\anaconda\envs\py37\lib\site-packages\xrt\runner.py", line 211, in one_iteration
    bl.forceAlign = False
AttributeError: 'NoneType' object has no attribute 'forceAlign'
```
If I operate the code '00_simple.py'in the github https://github.com/kklmn/xrt/tree/master/examples/withShadow/00_02
```
# -*- coding: utf-8 -*-
"""The simplest example of using shadow with xrt."""
__author__ = "Konstantin Klementiev"
__date__ = "1 Mar 2012"
import sys
sys.path.append(r"c:\Alba\Ray-tracing\with Python")
import xrt.runner as xrtr
import xrt.plotter as xrtp
plot1 = xrtp.XYCPlot('star.01')
plot1.caxis.fwhmFormatStr = None
xrtr.run_ray_tracing(plot1, repeats=40, updateEvery=2, backend='shadow')
````
there is also something wrong about the program,and always print the massege "('not readable',) , ignored..."
 I don't understand where is the problem is. But using the backend of shadow is very important to accomplish my experiment. please help me.
I wish to hear from you again

**Comment by kklmn** [comment]
Hi,

I've now fixed the Shadow backend (please download from GitHub) and checked it with the example `...\examples\withShadow\00_02\00_simple.py`.

I ran it with Shadow 2.3, and I've never tried a newer version. It can be that newer versions do not produce bat files anymore. Then you have to create shadow-source.bat and shadowvui.bat yourself.

The 'not readable' error may still appear from time to time due to concurrent file reading-writing.
If every iteration results in this error then Shadow doesn't produce the expected resulting files. In this case, run shadow-source.bat and shadowvui.bat from the command shell and explore the output.

**Comment by Zeng24** [comment]
Thanks a lot that you solve the problem of backend. I think the application you develop is very good, but I wanna use it to handle the data from Shadow3, and translate the data into the picture to absorve the beam like xrtglow'picture. How should I do?

**Comment by kklmn** [comment]
To use Shadow3 in xrt would mean a new backend. Since none of us needs it, we are not going to develop it.

Only if you (or another interested person) can provide a proper readout function, similar to 
xrt.backends.shadow.get_output(), I can look at connecting Shadow3 to xrt.

**Comment by Zeng24** [comment]
OK, thank you for your help.
