### ISSUE TITLE
    TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by wangm23456** [kklmn/xrt#5]
➤ pip install xrt
Collecting xrt
  Downloading xrt-1.2.0.zip (6.4MB)
    100% |████████████████████████████████| 6.4MB 13kB/s 
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/xrt.egg-info
    writing dependency_links to pip-egg-info/xrt.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/xrt.egg-info/top_level.txt
    writing pip-egg-info/xrt.egg-info/PKG-INFO
    **Traceback (most recent call last):**
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-4vyio9ge/xrt/setup.py", line 155, in <module>
        'Topic :: Scientific/Engineering :: Visualization'],
      File "/home/inat/APP/anaconda3/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/inat/APP/anaconda3/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/inat/APP/anaconda3/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/inat/APP/anaconda3/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/setuptools/command/egg_info.py", line 186, in run
      File "/home/inat/APP/anaconda3/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/setuptools/command/egg_info.py", line 397, in write_pkg_info
      File "/home/inat/APP/anaconda3/lib/python3.5/distutils/dist.py", line 1107, in write_pkg_info
        self.write_pkg_file(pkg_info)
      File "/home/inat/APP/anaconda3/lib/python3.5/distutils/dist.py", line 1122, in write_pkg_file
        file.write('Author: %s\n' % self.get_contact())
    **TypeError: not all arguments converted during string formatting**

**Comment by kklmn** [comment]
distutils.core.setup function in Python 3 obviously does not allow a list or a tuple of strings in 'author' field. The tuple ('Konstantin Klementiev', 'Roman Chernikov') will be changed to a string 'Konstantin Klementiev, Roman Chernikov' in the next release.
