### ISSUE TITLE
xrtGlow connot open

### ISSUE THREAD

**Issue by ToyLion** [kklmn/xrt#64]
Hi, I try to open xrtGlow with the ...\xrt-1.3.4\examples\withRaycing\_QookBeamlines\lens3.xml and BioXAS_Main.xml, after click the 3D glasses button, they both error.

Below the traceback:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\xrt\gui\xrtGlow\__init__.py", line 4117, in initializeGL
    gl.glViewport(*self.viewPortGL)
  File "C:\ProgramData\Anaconda3\lib\site-packages\OpenGL\platform\baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'\xce\xde\xd0\xa7\xb2\xd9\xd7\xf7',
        baseOperation = glViewport,
        cArguments = (0, 0, 500, 500)
)

My system showed in the right window of xrtQook:
Windows-10, Python 3.7.6
Qt 5.9.6, PyQt5 5.9.2
OpenGL 3.1.1a1
pyopencl 2020.2
xrt 1.3.4 in C:\ProgramData\Anaconda3\lib\site-packages, this is the latest version at PyPI

Is anything wrong with the OpenGL? How can I solve this problem?

Thanks!

**Comment by kklmn** [comment]
Try to install pyopengl and pyopengl-accelerate from [Gohlke](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyopengl).

**Comment by ToyLion** [comment]
I have reinstalled pyopengl and pyopengl-accelerate from Gohlke, but the error still exists.

My system changed: 
Windows-10, Python 3.7.6
Qt 5.9.6, PyQt5 5.9.2
OpenGL 3.1.5
pyopencl 2020.2
xrt 1.3.4 in C:\ProgramData\Anaconda3\lib\site-packages, this is the latest version at PyPI


The error:
(base) PS C:\xrt-1.3.4\xrt-1.3.4\xrt\gui> python xrtQookStart.pyw
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\xrt\gui\xrtGlow\__init__.py", line 4117, in initializeGL
    gl.glViewport(*self.viewPortGL)
  File "C:\ProgramData\Anaconda3\lib\site-packages\OpenGL\platform\baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "src\errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'\xce\xde\xd0\xa7\xb2\xd9\xd7\xf7',
        baseOperation = glViewport,
        cArguments = (0, 0, 500, 500)
)


The error is the same as before.


> Try to install pyopengl and pyopengl-accelerate from [Gohlke](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyopengl).

**Comment by kklmn** [comment]
Because you're using anaconda, another thing to try:
```
./conda remove pyopengl freeglut  # from anaconda/bin
./conda install -c conda-forge pyopengl freeglut # from anaconda/bin
```

**Comment by ToyLion** [comment]
Still error, but a different:

(base) PS C:\xrt-1.3.4\xrt-1.3.4\xrt\gui> python xrtQookStart.pyw                                                       Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\xrt\gui\xrtGlow\__init__.py", line 4115, in initializeGL
    gl.glutInit()
  File "C:\ProgramData\Anaconda3\lib\site-packages\OpenGL\GLUT\special.py", line 333, in glutInit
    _base_glutInit( ctypes.byref(count), holder )
  File "C:\ProgramData\Anaconda3\lib\site-packages\OpenGL\platform\baseplatform.py", line 425, in __call__
    self.__name__, self.__name__,
OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling


The xrtQoot window show:
Windows-10, Python 3.7.6
Qt 5.9.6, PyQt5 5.9.2
OpenGL 3.1.5 but GLUT is not found
pyopencl 2020.2
xrt 1.3.4 in C:\ProgramData\Anaconda3\lib\site-packages, this is the latest version at PyPI


After reinstalled the pyOpenGL from Gohlke , xrtQoot window show no wrong, but it's back to the error in anaconda shell.

**Comment by kklmn** [comment]
I see that in the last try `glut` was not installed properly. Again uninstall pyopengl and freeglut:
```
./conda remove pyopengl freeglut  # from anaconda/bin
```
And this time install pyopengl and freeglut separately:
```
./conda install -c conda-forge pyopengl # from anaconda/bin
./conda install -c conda-forge freeglut # from anaconda/bin
```
and see what was wrong in installing freeglut.

**Comment by ToyLion** [comment]
The install procedure:

(base) PS C:\ProgramData\Anaconda3> conda install -c conda-forge freeglut                                               Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\ProgramData\Anaconda3

  added / updated specs:
    - freeglut


The following NEW packages will be INSTALLED:

  freeglut           conda-forge/win-64::freeglut-3.0.0-h6538335_1005


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done


It seems to be all right? But the glut still not found.

**Comment by kklmn** [comment]
Again remove glut and try to install it with `-v` option to have it more verbose. Beforehand, I would also update [the current Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019 for Python 3](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).

**Comment by kklmn** [comment]
If you still can't solve it, I recommend WinPython. I personally find it more comfortable than Anaconda.

**Comment by ToyLion** [comment]
I try to update python with  'conda update --all', the process is extremely  slow. Some did not succeed, so I planned to update them several times until they were all completed. If it still doesn't work, I'll uninstall the anaconda and follow your advice.
Thank you for your patience!

**Comment by ToyLion** [comment]
xrtGlow finally works properly when I changed a computer. The installation went well this time. pip install xrt with shell, pyopencl, pyopengl and pyopengl-accelerate were downloaded from Gohlke.

**Comment by ToyLion** [comment]
Previous computers can also run xrtGlow correctly after fixing graphics driver.

**Comment by kklmn** [comment]
ok, thanks for sharing it!
