### ISSUE TITLE
pythonplatform.linux_distribution() and Python 3.8

### ISSUE THREAD

**Issue by weltere** [kklmn/xrt#65]
Trying to start xrtQook on a Linux Mint 20 machine I got the following error:
(base) weltere@edmund-laptop:~/Programme/xrt-1.3.4/xrt/gui$ python3 xrtQookStart.pyw
qt5ct: using qt5ct plugin
qt5ct: D-Bus system tray: no
Traceback (most recent call last):
  File "xrtQookStart.pyw", line 28, in <module>
    ex = xQ.XrtQook()
  File "../../xrt/gui/xrtQook/__init__.py", line 245, in __init__
    self.initAllTrees()
  File "../../xrt/gui/xrtQook/__init__.py", line 707, in initAllTrees
    self.showWelcomeScreen()
  File "../../xrt/gui/xrtQook/__init__.py", line 1073, in showWelcomeScreen
    locos = " ".join(pythonplatform.linux_distribution())
AttributeError: module 'platform' has no attribute 'linux_distribution'

For the time being I commented the two lines (1072 and 1073).
        #if 'Linux' in locos:
        #    locos = " ".join(pythonplatform.linux_distribution())

After this xrtQook starts without issues. It seems the problem is caused by the used Python version (Python 3.8.5).

Cheers,
Edmund

**Comment by kklmn** [comment]
Hi Edmund,
Indeed, they suddenly removed platform.linux_distribution() in Python 3.8. The GH version has a fix, probably we should issue a new release.
