### ISSUE TITLE
Encountered some issue with using xrtGlow

### ISSUE THREAD

**Issue by zzw840** [kklmn/xrt#85]
Hi I ran on xrtGlow on a x64 windows PC with python 3.5. I encountered this:

`Traceback (most recent call last):
  File "C:\Users\(myname)\Anaconda3\lib\site-packages\xrt\gui\xrtGlow\__init__.py", line 2481, in paintGL
    pModel = np.array(gl.glGetDoublev(gl.GL_MODELVIEW_MATRIX))[:-1, :-1]
  File "src\latebind.pyx", line 39, in OpenGL_accelerate.latebind.LateBind.__call__
  File "src\wrapper.pyx", line 303, in OpenGL_accelerate.wrapper.Wrapper.__call__
  File "src\wrapper.pyx", line 88, in OpenGL_accelerate.wrapper.CArgCalculator.c_call
  File "src\wrapper.pyx", line 69, in OpenGL_accelerate.wrapper.CArgCalculatorElement.c_call
  File "src\wrapper.pyx", line 64, in OpenGL_accelerate.wrapper.CArgCalculatorElement.c_call
  File "src\arraydatatype.pyx", line 355, in OpenGL_accelerate.arraydatatype.SizedOutputOrInput.c_call
  File "src\arraydatatype.pyx", line 224, in OpenGL_accelerate.arraydatatype.ArrayDatatype.c_zeros
  File "src\arraydatatype.pyx", line 69, in OpenGL_accelerate.arraydatatype.HandlerRegistry.c_get_output_handler
  File "src\arraydatatype.pyx", line 80, in OpenGL_accelerate.arraydatatype.HandlerRegistry.c_handler_by_plugin_name
  File "C:\Users\(myname)\Anaconda3\lib\site-packages\OpenGL\plugins.py", line 16, in load
    return importByName( self.import_path )
  File "C:\Users\(myname)\Anaconda3\lib\site-packages\OpenGL\plugins.py", line 38, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "C:\Users\(myname)\Anaconda3\lib\site-packages\OpenGL\arrays\numpymodule.py", line 28, in <module>
    from OpenGL_accelerate.numpy_formathandler import NumpyHandler
  File "__init__.pxd", line 918, in init OpenGL_accelerate.numpy_formathandler
ValueError: ('numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject', 1, <OpenGL.platform.baseplatform.glGetDoublev object at 0x0000020D6DAE76C0>)`

**Comment by kklmn** [comment]
Hi,
If the error is reproducible, I guess this is an incompatibility of OpenGL and numpy.
I do not use old versions of WinPython or Anaconda, so I never run into incompatibility problems. Unless you have reasons to keep this stone-age version, I'd recommend installing a new Python distribution.
