### ISSUE TITLE
Oval GaussianBeam 

### ISSUE THREAD

**Issue by leahwang1962** [kklmn/xrt#96]
Hi, 
Can I define an oval gaussian beam source if the beam waist FWHMs are different in 2 direction? Thanks.

class xrt.backends.raycing.sources.GaussianBeam(bl=None, name='', center=(0, 0, 0), w0=0.1, distE='lines', energies=(9000.0, ), energyWeights=None, polarization='horizontal', pitch=0, yaw=0)

**Comment by kklmn** [comment]
Hi,

I've added it now. Get it from GH.

The beam profile can be different in horizontal and vertical:
<img src="https://user-images.githubusercontent.com/17322580/155169909-0937876a-21c9-4c82-8cc1-eb41995e5cba.png" width="350" height="300">
Specify w0 as a 2-sequence.

The test `tests/raycing/laguerre_hermite_gaussian_beam.py` gives at the origin with `w0 = 30e-3, 15e-3`:
<img src="https://user-images.githubusercontent.com/17322580/155170222-5e5fe176-f670-421d-9dea-b329afea1936.png" width="489" height="315">

...and at 40 m by the analytical expression:
<img src="https://user-images.githubusercontent.com/17322580/155170416-9c85e462-fba0-462a-be90-b37626e7ba58.png" width="489" height="315">

...and at 40 m by the Kirchhoff integral:
<img src="https://user-images.githubusercontent.com/17322580/155170540-bf325a3d-2e6c-4338-8fcc-c6507560f26e.png" width="489" height="315">

Good luck!

**Comment by leahwang1962** [comment]
Really appreciate your addition.
When I run it, I got memory error as below.  Do you have version using less memory? I use windows and 8GB Ram. my project is related with xray tracing, but much simpler than synchrotron beamlines.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Python\lib\site-packages\xrt\multipro.py", line 265, in run
    raycing_output = raycing.run.run_process(self.card.beamLine)
  File "C:\Pycharm\Projects\20220222_xrt\tests\raycing\laguerre_hermite_gaussian_beam.py", line 323, in run_process
    rw.diffract(beamSource, waveOnFSMk)
  File "C:\Python\lib\site-packages\xrt\backends\raycing\waves.py", line 662, in diffract
    Es, Ep, aE, bE, cE = kcode(oeLocal, n, nl, wave, good)
  File "C:\Python\lib\site-packages\xrt\backends\raycing\waves.py", line 779, in _diffraction_integral_conv
    a = wave.xDiffr[:, np.newaxis] - oeLocal.x[good]
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 32.0 GiB for an array with shape (65536, 65536) and data type float64

**Comment by kklmn** [comment]
If you want wave propagation, you do need a high-performance machine as warned [here](https://xrt.readthedocs.io/raycing.html#usage). You don't have to do wave propagation for this particular example (set `wantKirchhoff = False` here). It only serves a nice comparative demonstration purpose.

**Comment by leahwang1962** [comment]
Great. set wantKirchhoff = False is fine with my project.
When I set wo=0 or wo=0, 20e-3 I got exception as below. How can I make this program work for point source or line source?


Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Pycharm\Projects\20220222_xrt\xrt\multipro.py", line 320, in run
    xh, xhRGB, xbe = self.do_hist1d(x, flux, cDataRGB, plot.xaxis)
  File "C:\Pycharm\Projects\20220222_xrt\xrt\multipro.py", line 80, in do_hist1d
    hist1d, binEdges = histogram(
  File "<__array_function__ internals>", line 180, in histogram
  File "C:\Pycharm\Projects\venv\lib\site-packages\numpy\lib\histograms.py", line 793, in histogram
    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
  File "C:\Pycharm\Projects\venv\lib\site-packages\numpy\lib\histograms.py", line 426, in _get_bin_edges
    first_edge, last_edge = _get_outer_edges(a, range)
  File "C:\Pycharm\Projects\venv\lib\site-packages\numpy\lib\histograms.py", line 315, in _get_outer_edges
    raise ValueError(
ValueError: supplied range of [nan, nan] is not finite

**Comment by leahwang1962** [comment]
Got it. Thanks.
